# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toDoListApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 575)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 31))
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(20, 60, 51, 31))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(20, 100, 51, 31))
        self.label3.setObjectName("label3")
        self.lineEditName = QtWidgets.QLineEdit(Dialog)
        self.lineEditName.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditSurname = QtWidgets.QLineEdit(Dialog)
        self.lineEditSurname.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.lineEditDay = QtWidgets.QLineEdit(Dialog)
        self.lineEditDay.setGeometry(QtCore.QRect(80, 110, 113, 20))
        self.lineEditDay.setObjectName("lineEditDay")
        self.pushButtonAccept = QtWidgets.QPushButton(Dialog)
        self.pushButtonAccept.setGeometry(QtCore.QRect(80, 150, 75, 23))
        self.pushButtonAccept.setObjectName("pushButtonAccept")
        self.labelDetails = QtWidgets.QLabel(Dialog)
        self.labelDetails.setGeometry(QtCore.QRect(10, 200, 391, 31))
        self.labelDetails.setText("")
        self.labelDetails.setObjectName("labelDetails")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 270, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditEnterTask = QtWidgets.QLineEdit(Dialog)
        self.lineEditEnterTask.setGeometry(QtCore.QRect(80, 250, 371, 41))
        self.lineEditEnterTask.setObjectName("lineEditEnterTask")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 340, 71, 16))
        self.label_3.setObjectName("label_3")
        self.listWidgetToDoList = QtWidgets.QListWidget(Dialog)
        self.listWidgetToDoList.setGeometry(QtCore.QRect(10, 370, 241, 121))
        self.listWidgetToDoList.setObjectName("listWidgetToDoList")
        self.pushButtonAddTask = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddTask.setGeometry(QtCore.QRect(80, 300, 75, 23))
        self.pushButtonAddTask.setObjectName("pushButtonAddTask")
        self.listWidgetCompletedTasks = QtWidgets.QListWidget(Dialog)
        self.listWidgetCompletedTasks.setGeometry(QtCore.QRect(280, 370, 241, 121))
        self.listWidgetCompletedTasks.setObjectName("listWidgetCompletedTasks")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(370, 340, 91, 16))
        self.label_4.setObjectName("label_4")
        self.pushButtonDelCompletedTasls = QtWidgets.QPushButton(Dialog)
        self.pushButtonDelCompletedTasls.setGeometry(QtCore.QRect(350, 510, 111, 23))
        self.pushButtonDelCompletedTasls.setObjectName("pushButtonDelCompletedTasls")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name:"))
        self.label2.setText(_translate("Dialog", "Surname:"))
        self.label3.setText(_translate("Dialog", "Day:"))
        self.pushButtonAccept.setText(_translate("Dialog", "Accept"))
        self.label_2.setText(_translate("Dialog", "Enter Task:"))
        self.label_3.setText(_translate("Dialog", "To-do list:"))
        self.pushButtonAddTask.setText(_translate("Dialog", "Add Task"))
        self.label_4.setText(_translate("Dialog", "Completed Tasks:"))
        self.pushButtonDelCompletedTasls.setText(_translate("Dialog", "<<< Undone Task"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
